### ISSUE TITLE
Boostercounter class

### ISSUE THREAD

**Issue by bmusalli** [oscarliang7/Android-MatchGame#1]
Hello,
When we ise bombs , gloves and hammers in the game, the numbet drops below zero and you use it as you press , I am trying to do it in the cide , but I couldnt find a solution , can you help? 
Boostercounter class, it doesnt go below zero, I fixed it, but it works with pressure.
I am waiting for your reply

**Comment by natygames** [comment]
Hi, @bmusalli, thanks for your reply, I solved this problem by adding if statement to checking the booster count is > 0 when pressing button.

**Comment by bmusalli** [comment]
thank you oscar, I just started trying to learn the software. I'm writing
to you from turkey.

25 Mayıs 2023 Perşembe tarihinde Oscar Liang ***@***.***>
yazdı:
